# ref. https://github.com/rust-lang/rustfmt/blob/master/Configurations.md
edition = "2021"
max_width = 100
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Default"
reorder_imports = true
merge_derives = true
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true